source 'http://rubygems.org'

gem 'rails', '~> 3.0.10'

gem 'annotate'
gem 'capybara'
gem 'cucumber-rails'
gem 'formtastic'#, :path => '../../formtastic'
gem 'rspec-rails'
gem 'steak'
gem 'database_cleaner'
gem 'haml-rails'
gem 'sass'
gem 'jquery-rails'
gem 'launchy'
gem 'nifty-generators'
gem 'pickle'
gem 'rails3-jquery-autocomplete', :path => '../'
gem 'simple_form'
gem 'sqlite3-ruby', :require => 'sqlite3'

# Test Mongo
# gem 'mongoid'
# gem 'bson_ext'
